### ISSUE TITLE
Add PoseNot implementation

### ISSUE THREAD

**Issue by lgerhardt45** [lgerhardt45/Jointify#13]
The `ProcessingView` offers `analyseVideo(frames: [UIImage]) -> [MeasurementFrame]`  in which the model and computation is to be implemented. The method takes an UIImage array, runs the model on each image and creates a `MeasurementFrame` instance for it. All UIImages converted to MeasurementFrames are returned.

Right now, a frame is taken each second of the video but should be changeable in `transformVideoToImageArray(videoUrl:)`. The left-or-right-knee choice is not implemented yet, I would say go for just left (default) for now. 

The images are shown in the `VideoResultView` in a ScrollView for now - that should make dev/ debugging easier). The proper VideoResultView (with the selected image above a strip of the frames) is yet to be implemented (see #12).

**Comment by BergmuellerNiklas** [comment]
Done.
